---
- name: Make src directory
  file: path={{SOURCE_LOCATION}} state=directory mode=0777
- name: Install Git 
  apt: name=git state=latest update_cache=yes
- name : Install python 2.7
  apt: name=python2.7
- name: Make pip src directory
  file: path={{SOURCE_LOCATION}}{{PIP_INSTALL_LOCATION}} state=directory
- name: Download easy python install
  get_url:
    url: https://bootstrap.pypa.io/ez_setup.py
    dest: "{{SOURCE_LOCATION}}{{PIP_INSTALL_LOCATION}}"
- name: easy_install pip
  command: easy_install pip
  args:
    chdir: "{{SOURCE_LOCATION}}{{PIP_INSTALL_LOCATION}}"
