---
- hosts: SMRTonFHIRApps
- vars:
  SMRTonFHIRAppList: [ 'ucb_app' ]
  PIP_INSTALL_LOCATION: "~"
  APP_INSTALL_LOCATION: "~"
  REPO_SRC_LOCATION: "git://github.gatech.edu/I3L/FHIRRelay.git"
- tasks:
  - block: Install flask and dependencies
    - name: install virtualEnv
      pip: name=virtualEnv
    - name: install flask
      pip: name=Flask version=0.11
      become: true
      become_user: root
    - name: install fhirclient
      pip: name=fhirclient

  - block: Pull down the flask apps and run them
    - name: Pull down the application repository
      git:
        args:
          repo: {{REPO_SRC_LOCATION}}
          dest: {{APP_INSTALL_LOCATION}}
    ***NOTE_IF_YOU_WANT_SOME_NETWORK_SETUP_IN_THE_APPS_DO_IT_HERE***
    - name: make virtual environment
      command: virtualenv venv
        args:
          chdir: APP_INSTALL_LOCATION
    - name: enter virtual environment
      command: . venv/bin/activate
        args:
          chdir: APP_INSTALL_LOCATION
    - name: Run SMRTonFHIRApp
      command: python {{ items }}
      with_items: {{SMRTonFHIRAppList}}
